# Generated by Django 5.0.7 on 2024-07-30 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_delete_payment"),
        ("users", "0003_remove_payment_course_or_lesson_payment_paid_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={"verbose_name": "Оплата", "verbose_name_plural": "Оплаты"},
        ),
        migrations.RemoveField(
            model_name="payment",
            name="date_payment",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_amount",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="user",
        ),
        migrations.AddField(
            model_name="payment",
            name="datetime_payment",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="дата оплаты"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="link",
            field=models.URLField(
                blank=True, max_length=400, null=True, verbose_name="Ссылка на оплату"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to=settings.AUTH_USER_MODEL,
                verbose_name="пользователь",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_type",
            field=models.CharField(
                choices=[("Наличные", "Cash"), ("Переводом", "Transfer")],
                default="Наличные",
                max_length=16,
                verbose_name="способ оплаты",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="сумма оплаты"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name=" id сессии"
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="materials.course",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paid_lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment",
                to="materials.lesson",
            ),
        ),
    ]
