# Generated by Django 5.0.7 on 2024-08-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_options_remove_payment_date_payment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Заходил в последний раз"
            ),
        ),
    ]
