# Generated by Django 5.0.7 on 2024-07-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_payment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Payment",
        ),
    ]
